version: '3.8'

services:
  node:
    build: ./server
    ports:
      - 8080:8080
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - 3000:80
    depends_on:
      - node
    