version: '3.8'

services:
  node:
    build: ./server
    ports:
      - 8000:8080
    volumes:
      - ./server/:/usr/src/app
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - 3000:5173
    # volumes:
    #   - ./client/:/app
    depends_on:
      - node
    